name: nerostr-paywall-dockerhub

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nerostr
          file: ./nerostr/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ format('{0}/nerostr:{1}', secrets.DOCKERHUB_USERNAME, github.event.release.tag_name) }}
            ${{ format('{0}/nerostr:latest', secrets.DOCKERHUB_USERNAME) }}
